import { Inter } from "next/font/google";
import LeftSidebar from "@/components/LeftSidebar";
import "../globals.css";
import AuthContext from "@/components/AuthContext";
import { Toaster } from 'react-hot-toast';
import Topbar from "@/components/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "LinkedList - Profile",
    description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-[#F0F2F4]`}>
                <AuthContext>
                    <Toaster />
                    <main className="flex">
                        <LeftSidebar />
                        <div className="w-full p-5 md:p-10">
                            <Topbar />
                            {children}
                        </div>
                    </main>
                </AuthContext>
            </body>
        </html>
    )
}
